### ISSUE TITLE
Feature Suggestions : Custom balanced mode

### ISSUE THREAD

**Issue by AdmiralElectron** [TheDogKSP/MoreEffectiveTransfer#5] opened 2022-02-12 10:15 UTC
Feature Suggestions :

Instead of making dedicated local and Import/export modes of warehouses, we can rework existing balanced modes a little bit.

The proposed functioning would ensure that warehouses try to buy/sell from local warehouses within a certain range instead of immediately going to import/export.

Currently, the balanced warehouse mode works as the following image shows.

![image](https://user-images.githubusercontent.com/68630007/153707135-96358503-0290-4832-8dfb-152e2afad475.png)

The proposed rework of balanced warehouse mode is as below.
![image](https://user-images.githubusercontent.com/68630007/153707153-86ffe895-5761-41f8-ac3f-b402537316b7.png)

If possible, we can add custom modes with user-configurable inventory levels and custom buy/sell behaviour. 

The exact configuration and testing might be needed to iron out any rare cases.

**Comment by TheDogKSP** [comment] 2022-02-12 13:23
duplicate of #4  - closing this one

**Closed by TheDogKSP** 2022-02-12 13:23 UTC
